### ISSUE TITLE
Warning: Internal React error: Expected static flag was missing. Please notify the React team.

### ISSUE THREAD

**Issue by wengtytt** [HenrikBechmann/react-infinite-grid-scroller#20] opened 2023-01-05 18:57 UTC
With React 18, it always show the error below:

Warning: Internal React error: Expected static flag was missing. Please notify the React team.

**Comment by HenrikBechmann** [comment] 2023-01-05 19:06
Thanks @wengtytt.

Not getting that on the [demo site](https://henrikbechmann.github.io/rigs-demo/). Uses react 18.2.

Can you give more details on your environment, and the code fragment that configures the scroller?

Thanks.

**Comment by HenrikBechmann** [comment] 2023-01-05 19:13
Hmm. [This](https://github.com/facebook/react/issues/24391) suggests the problem is a conditional before hooks are run. 

I'll check...

**Comment by HenrikBechmann** [comment] 2023-01-05 19:38
I found three. Testing now.

**Comment by HenrikBechmann** [comment] 2023-01-05 20:16
Well, I moved those three pre-emptive returns, because it's good form. Uploaded the modifications to npm version 1.0.1.

But I couldn't reproduce the problem.

Could you try with 1.0.1? If you still have the problem could you show me the code that sets the scroller's properties, and the values of those properties?

**Comment by HenrikBechmann** [comment] 2023-01-06 22:28
I've checked with a linter, and there are no more conditional hooks.

I integrated multiple suggestions from the linter though, including a bug fix ("=" s/b "==")

I'll close this issue now, but feel free to re-open if the problem persists.

**Closed by HenrikBechmann** 2023-01-06 22:28 UTC
